apiVersion: batch/v1
kind: Job
metadata:
  name: flask-migrations
spec:
  template:
    spec:
      containers:
        - name: flask-migrate
          image: 135808944307.dkr.ecr.ap-south-1.amazonaws.com/message-app:latest
          command: ["flask", "db", "upgrade"]
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "postgresql://postgres:password@postgres/messages_db"
      restartPolicy: OnFailure
