apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-class
provisioner: kubernetes.io/aws-ebs #  AWS EBS
parameters:
  type: gp3 # General-purpose SSD (can vary by cloud provider)
  fsType: ext4
reclaimPolicy: Retain # Keeps the volume after release
